export const products = [
  {
    id: 1,
    category: "bracelet",
    name: "스와브로스키 진주은팔찌",
    price: 58000,
    description: "고급스러운 진주와 골드 체인 조합의 팔찌.",
    image: "./img/Swabrowski_Poodle_Pearl_Silver_Bracelet.jpg",
  },
  {
    id: 2,
    category: "bracelet",
    name: "로고 체인 팔찌",
    price: 185000,
    description: "감각적인 로고가 포인트인 체인 팔찌.",
    image: "https://via.placeholder.com/240x240?text=Bracelet+2",
  },
  {
    id: 3,
    category: "bracelet",
    name: "크리스탈 참 팔찌",
    price: 99000,
    description: "은은한 크리스탈 참이 돋보이는 팔찌.",
    image: "https://via.placeholder.com/240x240?text=Bracelet+3",
  },
  {
    id: 4,
    category: "bracelet",
    name: "골드 볼 팔찌",
    price: 135000,
    description: "심플한 골드 볼 디자인의 팔찌.",
    image: "https://via.placeholder.com/240x240?text=Bracelet+4",
  },
  {
    id: 5,
    category: "necklace",
    name: "진주 목걸이",
    price: 210000,
    description: "우아한 진주와 골드가 어우러진 목걸이.",
    image: "https://via.placeholder.com/240x240?text=Necklace+1",
  },
  {
    id: 6,
    category: "necklace",
    name: "펜던트 목걸이",
    price: 245000,
    description: "심플하면서도 고급스러운 펜던트 목걸이.",
    image: "https://via.placeholder.com/240x240?text=Necklace+2",
  },
  {
    id: 7,
    category: "necklace",
    name: "크리스탈 드롭 목걸이",
    price: 175000,
    description: "크리스탈 드롭이 포인트인 목걸이.",
    image: "https://via.placeholder.com/240x240?text=Necklace+3",
  },
  {
    id: 8,
    category: "necklace",
    name: "골드 체인 목걸이",
    price: 159000,
    description: "고급스러운 골드 체인 목걸이.",
    image: "https://via.placeholder.com/240x240?text=Necklace+4",
  },
];
